anomalyclip:
  checkpoint: ./checkpoints/9_12_4_mvtec_anomaly_detection+BR-A_1208+BR-C_1280/epoch_15.pth
  imgsz: 512 # 32*12
  threshold: 0.25
  min_area: 300

classifier:
  checkpoint: ./NAS/classify/weights/SSBR/2550H_imgsz32/weights/best.pt
  imgsz: 32 # 32*1
  threshold: 0.8

bgremover:
  checkpoint: ./NAS/segment/weights/rmbg/all/weights/best.pt
  imgsz: 160 # 32*5

sam2:
  checkpoint: ./NAS/segment/weights/sam2.1/sam2.1_hiera_tiny.pt
  config_name: sam2.1/sam2.1_hiera_t.yaml
  pred_iou_thresh: 0.0
  stability_score_thresh: 0.0
  points_per_side: 1

show:
  anomaly_map: false
  anomaly_score: true
  foreground: true