defect_detection:
  anomalyclip:
    checkpoint: ./checkpoints/anomalyclip/9_12_4_mvtec+F1038-F2150-M2520/epoch_15.pth
    imgsz: 512 # 32*16
    threshold: 0.25
    min_area: 0

  classifier:
    checkpoint: ./checkpoints/classify/weights/SSBR/_intergrated/weights/best.pt
    imgsz: 224 # 32*7
    threshold: 0.8

  bgremover:
    checkpoint: ./checkpoints/segment/weights/rmbg/all/weights/best.pt
    imgsz: 160 # 32*5

  segmenter:
    checkpoint: ./checkpoints/segment/weights/yolo_seg/SSBR_ALL/weights/best.pt
    imgsz: 224 # 32*7
    threshold: 0.0

  sam2:
    checkpoint: ./checkpoints/segment/weights/sam2.1/sam2.1_hiera_tiny.pt
    config_name: sam2.1/sam2.1_hiera_t.yaml
    pred_iou_thresh: 0.0
    stability_score_thresh: 0.0
    points_per_side: 1

  show:
    anomaly_map: false
    anomaly_score: true
    foreground: false
    anomaly_regions_polygon: true
    anomaly_regions_bbox: true
    segmentation_regions_polygon: true
    segmentation_regions_bbox: true
    show_pass_classes: true